### PR TITLE
Add MediatR Integration

### PR DESCRIPTION
**Pull request by jesmith026**

### CODE REVIEW

**Comment by tonysneed** [comment]
@jesmith026 Thanks so much! I'll review and merge.

**Comment by tonysneed** [comment]
@jesmith026 Could you do me a favor and format opening and closing curly braces per the [MS C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions). Also, please prefix private and internal fields with `_`. Thanks!

**Comment by jesmith026** [comment]
> @jesmith026 Could you do me a favor and format opening and closing curly braces per the [MS C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions). Also, please prefix private and internal fields with `_`. Thanks!

done

**Comment by tonysneed** [comment]
Great job @jesmith026  -- thank you very much!

**Pull request merged**
